# Generated by Django 2.0.13 on 2019-09-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantBlog', '0003_dish_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review1', to='RestaurantBlog.Dish'),
        ),
    ]
