# Generated by Django 2.0.13 on 2019-09-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantBlog', '0004_review_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review2', to='RestaurantBlog.Restaurant'),
        ),
    ]
