# Generated by Django 2.0.13 on 2019-09-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantBlog', '0005_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount'),
        ),
    ]
